### WORKSPACE RULES ###
workspace = 2, monitor:DP-2,  defaultName:vertical, persistent:true, layout:scrolling


dwindle {
    pseudotile = true 
    preserve_split = true # You probably want this
    smart_split = false # also turns on preseve_split
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
    new_status = master
}

scrolling {
    direction = down
    column_width = 0.5
    follow_focus = true
    follow_min_visible = 0.2
    focus_fit_method = 1
}
